apiVersion: v1
kind: Service
metadata:
  name: dmcld-simsrv-svc
  namespace: ${DMCLD_V1_NAMESPACE}
  labels:
    app: dmcld-simsrv-svc
spec:
  selector:
    app: dmcld-simsrv-deploy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
      name: simsrv  
  type: NodePort