apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dmcld-javaweb-deploy
  namespace: ${DMCLD_V1_NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dmcld-javaweb-deploy
    spec:
      containers:
      - name: web
        image: registry.cn-hangzhou.aliyuncs.com/dmcloudv1/javaweb:latest
        imagePullPolicy: Always
        #command: ["/bin/sh","cat /var/lib/tomcat6/webapps/web/WEB-INF/classes/database.properties"]
        ports:
        - containerPort: 8888
        volumeMounts:  
        - mountPath: /var/lib/tomcat6/webapps/web/WEB-INF/classes/database.properties
          subPath: database.properties
          name: dmcld-javaweb-config
      volumes:
        - name: dmcld-javaweb-config
          configMap:
            name: dmcld-javaweb-config
            items:
            - key: first # 使用configmap里面key对应的数据
              path: database.properties # 代表/var/lib/tomcat6/webapps/web/WEB-INFO/classes/database.properties文件              
      restartPolicy: Always