apiVersion: v1
kind: Service
metadata:
  name: dmcld-javaweb-svc
  namespace: ${DMCLD_V1_NAMESPACE}
  labels:
    app: dmcld-javaweb-svc
spec:
  selector:
    app: dmcld-javaweb-deploy
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 9999
  type: NodePort