apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dmcld-simsrv-deploy
  namespace: ${DMCLD_V1_NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dmcld-simsrv-deploy
    spec:
      containers:
      - name: simsrv
        image: registry.cn-hangzhou.aliyuncs.com/dmcloudv1/simsrv:01600014
        ports:
        - containerPort: 8080
        volumeMounts:  
        - mountPath: /dinstar/cfg # 这里是路径
          name: dmcld-simsrv-config
      volumes:
        - name: dmcld-simsrv-config
          configMap:
            name: dmcld-simsrv-config
            items:
            - key: first # 使用configmap里面key对应的数据
              path: config # 代表/dinstar/cfg/config文件           
      restartPolicy: Always