apiVersion: v1
kind: Service
metadata:
  name: ${DMCLD_V1_PROXY_NAME}-svc
  namespace: ${DMCLD_V1_NAMESPACE}
  labels:
    app: ${DMCLD_V1_PROXY_NAME}-svc
spec:
  selector:
    app: ${DMCLD_V1_PROXY_NAME}-deploy
  ports:
    - port: ${DMCLD_V1_PROXY_PORT}
      targetPort: ${DMCLD_V1_PROXY_PORT}
      nodePort: ${DMCLD_V1_PROXY_PORT}
  type: NodePort