apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${DMCLD_V1_PROXY_NAME}-deploy
  namespace: ${DMCLD_V1_NAMESPACE}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ${DMCLD_V1_PROXY_NAME}-deploy
    spec:
      nodeSelector:
        nodeResource: "normal"
      containers:
      - name: proxy
        image: ${DMCLD_V1_PROXY_IMAGE}
        imagePullPolicy: Always
#        resources:
#          limits:
#            memory: "${DMCLD_V1_PROXY_RESOURCE_LIMIT_MEM}"
#            cpu: "${DMCLD_V1_PROXY_RESOURCE_LIMIT_CPU}"
#          requests:
#            memory: "${DMCLD_V1_PROXY_RESOURCE_REQUEST_MEM}"
#            cpu: "${DMCLD_V1_PROXY_RESOURCE_REQUEST_CPU}"
        ports:
        - containerPort: ${DMCLD_V1_PROXY_PORT}
          protocol: ${DMCLD_V1_PROXY_PROTOCOL}
        volumeMounts:  
        - mountPath: /etc/config # 这里是路径
          name: ${DMCLD_V1_PROXY_NAME}-volume
      volumes:
        - name: ${DMCLD_V1_PROXY_NAME}-volume
          configMap:
            name: ${DMCLD_V1_PROXY_NAME}-config
            items:
            - key: first # 使用configmap里面key对应的数据
              path: config # 代表/etc/config/config文件
      restartPolicy: Always