apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${DMCLD_V1_PROXY_NAME}-deploy
  namespace: ${DMCLD_V1_NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${DMCLD_V1_PROXY_NAME}-deploy
    spec:
      containers:
      - name: proxy
        image: ${DMCLD_V1_PROXY_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: ${DMCLD_V1_PROXY_PORT}
        volumeMounts:  
        - mountPath: /etc/config # 这里是路径
          name: ${DMCLD_V1_PROXY_NAME}-volume
      volumes:
        - name: ${DMCLD_V1_PROXY_NAME}-volume
          configMap:
            name: ${DMCLD_V1_PROXY_NAME}-config
            items:
            - key: first # 使用configmap里面key对应的数据
              path: config # 代表/etc/config/config文件
      restartPolicy: Always