apiVersion: v1
data:
  first: |
    {
         "log":{
                 "path":"/opt/log",
                 "maxAge":0,
                 "rotation":0
          },
         "redis":{
                 "redisDNS":"${DMCLD_V1_PROXY_REDIS_ADDRESS}",
                 "redisPort":"${DMCLD_V1_PROXY_REDIS_PORT}",
                 "redisPassword":"${DMCLD_V1_PROXY_REDIS_PASSWORD}"
          },
          "mysql":{
                  "name":"${DMCLD_V1_PROXY_DB_ADDRESS}",
                  "user":"${DMCLD_V1_PROXY_DB_USER}",
                  "pass":"${DMCLD_V1_PROXY_DB_PASSWORD}",
                  "port":"${DMCLD_V1_PROXY_DB_PORT}",
                  "dbname":"${DMCLD_V1_PROXY_DB_NAME}"
          },
          "K8SDNS":"k8s-dmcldv1-master.dmcld.com",
          "Host":"172.17.0.1",
          "HostPort":"8080",
          "timeout":10
    }
  proxy-2022: |
    {
         "log":{
                 "path":"/opt/log",
                 "maxAge":0,
                 "rotation":0
          },
          "mysql":{
                  "name":"${DMCLD_V1_PROXY_DB_ADDRESS}",
                  "user":"${DMCLD_V1_PROXY_DB_USER}",
                  "pass":"${DMCLD_V1_PROXY_DB_PASSWORD}",
                  "port":"${DMCLD_V1_PROXY_DB_PORT}",
                  "dbname":"${DMCLD_V1_PROXY_DB_NAME}"
          },
          "timeout":{
                  "udp":5,
                  "cacheupdate":10,
                  "cacheexpir":5,
                  "cacheclean":10
          }
    }
  proxy-4042: |
    {
          "mysql":{
                  "host":"${DMCLD_V1_PROXY_DB_ADDRESS}",
                  "user":"${DMCLD_V1_PROXY_DB_USER}",
                  "pass":"${DMCLD_V1_PROXY_DB_PASSWORD}",
                  "port":"${DMCLD_V1_PROXY_DB_PORT}",
                  "db":"${DMCLD_V1_PROXY_DB_NAME}",
                  "db_all":"${DMCLD_V1_PROXY_DB_ALL_NAME}"
          },
          "default_svc_port":${DMCLD_V1_PROXY_DEFAULT_SVC_PORT}
    }
kind: ConfigMap
metadata:
  name: ${DMCLD_V1_PROXY_NAME}-config
  namespace: ${DMCLD_V1_NAMESPACE}