apiVersion: v1
kind: Service
metadata:
  name: ${DMCLD_V1_BASE}-svc
  namespace: ${DMCLD_V1_NAMESPACE}
  labels:
    app: ${DMCLD_V1_BASE}-svc
spec:
  selector:
    app: ${DMCLD_V1_BASE}-deploy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
      name: simsrv
    - port: 8888
      targetPort: 8888
      nodePort: 8888
      name: web     
  type: NodePort