apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-deploy
  namespace: ${DMCLD_V1_NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-deploy
    spec:
      containers:
      - name: web
        image: registry.cn-hangzhou.aliyuncs.com/dmcloudv1/javaweb:latest
        #command: ["/bin/sh","cat /var/lib/tomcat6/webapps/web/WEB-INF/classes/database.properties"]
        ports:
        - containerPort: 8888
        volumeMounts:  
        - mountPath: /dinstar/cfg # 这里是路径
          name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config
        #注意java配置以文件的形式挂载防止目录被覆盖
        - mountPath: /var/lib/tomcat6/webapps/web/WEB-INF/classes/database.properties
          subPath: database.properties
          name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config-java
      - name: simsrv
        image: registry.cn-hangzhou.aliyuncs.com/dmcloudv1/simsrv:01600014
        ports:
        - containerPort: 8080
        volumeMounts:  
        - mountPath: /dinstar/cfg # 这里是路径
          name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config
      volumes:
        - name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config
          configMap:
            name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config
            items:
            - key: first # 使用configmap里面key对应的数据
              path: config # 代表/dinstar/cfg/config文件
        - name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config-java
          configMap:
            name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-config
            items:
            - key: java # 使用configmap里面key对应的数据
              path: database.properties # 代表/var/lib/tomcat6/webapps/web/WEB-INFO/classes/database.properties文件              
      restartPolicy: Always