apiVersion: v1
kind: Service
metadata:
  name: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-svc
  namespace: ${DMCLD_V1_NAMESPACE}
  labels:
    app: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-svc
spec:
  selector:
    app: ${DMCLD_V1_BASE}-${DMCLD_V1_SERVER_ID}-deploy
  ports:
    - name: simsrv-http
      port: 8080
      targetPort: 8080
      nodePort: ${DMCLD_V1_SIMSRV_WEB_PROXY_PORT}
      protocol: TCP
    - name: simsrv-command
      port: 2022
      targetPort: 2022
      nodePort: ${DMCLD_V1_SIMSRV_NODE_PORT}
      protocol: UDP
    - port: 8888
      targetPort: 8888
      nodePort: ${DMCLD_V1_JAVAWEB_NODE_PORT}
      name: web
      protocol: TCP
  type: NodePort